fix [SDK 50] react-native-maps config plugin issue
```
Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/\s*get_default_flags\(\)/i" in contents:
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
```
に対応。  
https://github.com/expo/expo/issues/26539#issuecomment-1920868859